    watchDog.o: watchDog.cpp /opt/work/Hi3515a/src/lsdvs/../common/debug.h \
 /opt/work/Hi3515a/src/lsdvs/../common/const.h \
 /opt/work/Hi3515a/src/lsdvs/../common/thread.h \
 /opt/work/Hi3515a/src/lsdvs/../common/timer.h watchDog.h
