    broadcastServer.o: broadcastServer.cpp \
 /opt/work/Hi3515a/src/lsdvs/../common/debug.h \
 /opt/work/Hi3515a/src/lsdvs/../common/linuxFile.h \
 /opt/work/Hi3515a/src/lsdvs/../public/hton.h \
 /opt/work/Hi3515a/src/lsdvs/../common/const.h \
 /opt/work/Hi3515a/src/lsdvs/../common/thread.h \
 /opt/work/Hi3515a/src/lsdvs/../common/message.h \
 /opt/work/Hi3515a/src/lsdvs/../common/mutex.h \
 /opt/work/Hi3515a/src/lsdvs/../common/netSocket.h \
 /opt/work/Hi3515a/src/lsdvs/../common/const.h broadcastServer.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramConfig.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramConfDefault.h \
 /opt/work/Hi3515a/src/lsdvs/../public/ptypes.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramManage.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramConfig.h \
 /opt/work/Hi3515a/src/lsdvs/net/netDns.h \
 /opt/work/Hi3515a/src/lsdvs/net/netGateway.h \
 /opt/work/Hi3515a/src/lsdvs/net/netIp.h \
 /opt/work/Hi3515a/src/lsdvs/net/netMask.h \
 /opt/work/Hi3515a/src/lsdvs/net/netMac.h
