    ntpApp.o: ntpApp.cpp /opt/work/Hi3515a/src/lsdvs/../common/debug.h \
 /opt/work/Hi3515a/src/lsdvs/../common/thread.h ntpApp.h ntpclient.h \
 /opt/work/Hi3515a/src/lsdvs/../common/message.h \
 /opt/work/Hi3515a/src/lsdvs/../common/mutex.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramManage.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramConfig.h \
 /opt/work/Hi3515a/src/lsdvs/../common/const.h \
 /opt/work/Hi3515a/src/lsdvs/param/paramConfDefault.h \
 /opt/work/Hi3515a/src/lsdvs/../public/ptypes.h \
 /opt/work/Hi3515a/src/lsdvs/../common/timeExchange.h \
 /opt/work/Hi3515a/src/lsdvs/datetime/rtc.h \
 /opt/work/Hi3515a/src/lsdvs/datetime/realTime.h
    ntpclient.o: ntpclient.cpp /opt/work/Hi3515a/src/lsdvs/../common/debug.h \
 ntpApp.h
